### ISSUE TITLE
Master is broken and 1.1.1 too.

### ISSUE THREAD

**Issue by koddsson** [koddsson/gengi-cli#5]
```
☁  gengi-cli [master] npm install -g gengi-cli
/usr/local/bin/gengi -> /usr/local/lib/node_modules/gengi-cli/bin/gengi
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk requires assert-plus@'>=0.2.0 <0.3.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/assert-plus,
npm WARN unmet dependency which is version 0.1.5
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/dashdash requires assert-plus@'^0.2.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/assert-plus,
npm WARN unmet dependency which is version 0.1.5
gengi-cli@1.1.1 /usr/local/lib/node_modules/gengi-cli
├── promise@7.1.1 (asap@2.0.3)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
├── node-fetch@1.4.1 (is-stream@1.0.1, encoding@0.1.12)
├── babel-plugin-add-module-exports@0.1.2 (lodash@3.10.1, babel-template@6.7.0)
├── babel-preset-es2015@6.6.0 (babel-plugin-transform-es2015-parameters@6.7.0, babel-plugin-transform-es2015-object-super@6.6.5, babel-plugin-transform-es2015-computed-properties@6.6.5, babel-plugin-transform-es2015-classes@6.6.5, babel-plugin-transform-es2015-arrow-functions@6.5.2, babel-plugin-check-es2015-constants@6.7.2, babel-plugin-transform-es2015-for-of@6.6.0, babel-plugin-transform-es2015-literals@6.5.0, babel-plugin-transform-es2015-duplicate-keys@6.6.4, babel-plugin-transform-es2015-block-scoped-functions@6.6.5, babel-plugin-transform-es2015-shorthand-properties@6.5.0, babel-plugin-transform-es2015-sticky-regex@6.5.0, babel-plugin-transform-es2015-spread@6.6.5, babel-plugin-transform-es2015-function-name@6.5.0, babel-plugin-transform-es2015-typeof-symbol@6.6.0, babel-plugin-transform-es2015-block-scoping@6.7.1, babel-plugin-transform-es2015-destructuring@6.6.5, babel-plugin-transform-es2015-template-literals@6.6.5, babel-plugin-transform-es2015-modules-commonjs@6.7.4, babel-plugin-transform-es2015-unicode-regex@6.5.0, babel-plugin-transform-regenerator@6.6.5)
└── babel-register@6.7.2 (path-exists@1.0.0, home-or-tmp@1.0.0, mkdirp@0.5.1, source-map-support@0.2.10, babel-core@6.7.4, lodash@3.10.1, babel-runtime@5.8.38, core-js@2.2.1)
☁  gengi-cli [master] gengi
/usr/local/lib/node_modules/gengi-cli/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import args from './args'
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/gengi-cli/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gengi-cli/index.js:2:1)
    at Module._compile (module.js:435:26)
☁  gengi-cli [master]
```

**Comment by koddsson** [comment]
cc/ @benediktvaldez

**Comment by koddsson** [comment]
I've added you as a collaborator so if you wanna tackled this you can just get it straight into master. Just remember to do 

> git tag -a "1.1.1" -m "`git log -1 --format=%s`" && git push origin master --tags

to give out a new version and travis will make sure to get it into npm.

**Comment by koddsson** [comment]
This keeps getting formatted weird. Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/318208/14094656/caef8ca8-f547-11e5-8e30-cbdd5c420934.png)

**Comment by benediktvaldez** [comment]
hmm interesting - I get the same error, except when I navigate locally to `usr/local/lib/node_modules/gengi-cli`

Think it's a babel issue - working on a fix

``` shell
➜  ~ gengi
/usr/local/lib/node_modules/gengi-cli/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import args from './args'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/gengi-cli/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/gengi-cli/index.js:2:1)
    at Module._compile (module.js:413:34)
➜  ~ cd /usr/local/lib/node_modules/gengi-cli
➜  gengi-cli git:(master) gengi
usage: gengi <currency> <value> [-r | --round] [-h | --help]

currency:     Standard three letter currency code (ISO 4217)
value:        Numeric value, defaults to 1
-r | --round: Round calculated number
-h | --help:  Show these instructions

Other available commands
gengi list    Display list of all available currencies
➜  gengi-cli git:(master)
```

**Comment by benediktvaldez** [comment]
FINALLY

solved @koddsson :stuck_out_tongue_winking_eye:

**Comment by koddsson** [comment]
![](https://31.media.tumblr.com/tumblr_m7wha6r7EK1qzqdem.gif)
